export const contactData = [
  {
    id: 1,
    fullName: "Marcus Ellison, Esq.",
    type: "Attorney",
    phone: "303-333-3333",
    email: "joe@velarium.com",
    notes: "",
    isPrimary: false,
  },
  {
    id: 2,
    fullName: "Sgt. Maria Bennett,",
    type: "Union Rep",
    phone: "303-333-3333",
    email: "mbennett@email.com",
    notes: "District 2 Union Rep.",
    isPrimary: true,
  },
  {
    id: 3,
    fullName: "Lt. Deborah Hall",
    type: "Supervisor",
    phone: "303-333-3333",
    email: "dhall@email.com",
    notes: "",
    isPrimary: false,
  },
  {
    id: 4,
    fullName: "Vivian Drost",
    type: "Arbitrator",
    phone: "303-333-3333",
    email: "vdrost@email.com",
    notes: "",
    isPrimary: false,
  },
  {
    id: 5,
    fullName: "Joshua Martin",
    type: "Witness",
    phone: "303-333-3333",
    email: "jmartin@email.com",
    notes: "",
    isPrimary: false,
  },
];
