export const fieldHeadData = [
  { id: 1, label: "First Name" },
  { id: 2, label: "Last Name" },
  { id: 3, label: "Email" },
  { id: 4, label: "Phone #" },
  { id: 5, label: "Role" },
  { id: 6, label: "Status" },
  { id: 7, label: "Action" },
];

export const fieldCellData = [
  {
    id: 1,
    firstName: "Joel",
    lastName: "Rosen",
    email: "joel@velarium.com",
    phone: "(720) 555-2287",
    role: "Administrator",
    status: "Active",
  },
  {
    id: 2,
    firstName: "Mary",
    lastName: "Fynn",
    email: "Mary@youremail.net",
    phone: "(303) 555-1143",
    role: "Administrator",
    status: "Active",
  },
  {
    id: 3,
    firstName: "Aaron",
    lastName: "Erickson",
    email: "aerickson@youremail.net",
    phone: "(303) 555-0098",
    role: "Accounting",
    status: "Active",
  },
  {
    id: 4,
    firstName: "John",
    lastName: "Smith",
    email: "jsmith@youremail.com",
    phone: "(303) 555-5276",
    role: "Office Admin",
    status: "Inactive",
  },
  {
    id: 5,
    firstName: "Carole",
    lastName: "Martin",
    email: "cmartin@youremail.net",
    phone: "(720) 555-7933",
    role: "IT",
    status: "Active",
  },
  {
    id: 6,
    firstName: "Jessie",
    lastName: "O’Donell",
    email: "jessie@youremail.net",
    phone: "(303) 555-8845",
    role: "IT",
    status: "Inactive",
  },
  {
    id: 7,
    firstName: "Steve",
    lastName: "Brooks",
    email: "steve@youremail.net",
    phone: "(303) 555-4443",
    role: "Legal",
    status: "Active",
  },
  {
    id: 8,
    firstName: "Jeremy",
    lastName: "Jones",
    email: "jeremy@youremail.net",
    phone: "(970) 555-6744",
    role: "Office",
    status: "Active",
  },
  {
    id: 9,
    firstName: "Kevin",
    lastName: "Adams",
    email: "kadams@youremail.com",
    phone: "(720) 555-9271",
    role: "Front Desk",
    status: "Active",
  },
];
