export const meetingHeadData = [
  "Meeting Name",
  "Meeting Date",
  "Meeting Time",
  "Meeting Type",
  "Page #",
  "Line #",
  "Verified",
  "By",
  "Action",
];

// Sample data
export const initialMeetings = [
  {
    id: 1,
    name: "BOD",
    date: new Date("2025-02-14"),
    time: "11:00 AM",
    type: "Automatic",
    page: 244,
    line: 29,
    verified: "Check-in sheet",
    by: "Admin",
  },
  {
    id: 2,
    name: "BOD",
    date: new Date("2025-02-14"),
    time: "01:00 PM",
    type: "Automatic",
    page: 244,
    line: 29,
    verified: "QR Code",
    by: "Admin",
  },
  {
    id: 3,
    name: "GMM",
    date: new Date("2025-02-14"),
    time: "02:00 PM",
    type: "Automatic",
    page: 247,
    line: 20,
    verified: "Check-in sheet",
    by: "Admin",
  },
  {
    id: 4,
    name: "BOD",
    date: new Date("2025-02-14"),
    time: "11:00 AM",
    type: "Automatic",
    page: 244,
    line: 29,
    verified: "Check-in sheet",
    by: "Admin",
  },
  {
    id: 5,
    name: "BOD",
    date: new Date("2025-02-14"),
    time: "01:00 PM",
    type: "General",
    page: 244,
    line: 29,
    verified: "Check-in sheet",
    by: "Admin",
  },
  {
    id: 6,
    name: "BOD",
    date: new Date("2025-02-14"),
    time: "02:00 PM",
    type: "General",
    page: 244,
    line: 29,
    verified: "QR Code",
    by: "Admin",
  },
  {
    id: 7,
    name: "GMM",
    date: new Date("2025-02-14"),
    time: "11:00 AM",
    type: "General",
    page: 244,
    line: 29,
    verified: "Check-in sheet",
    by: "Admin",
  },
  {
    id: 8,
    name: "BOD",
    date: new Date("2025-02-14"),
    time: "11:00 AM",
    type: "Automatic",
    page: 244,
    line: 29,
    verified: "Check-in sheet",
    by: "Admin",
  },
  {
    id: 9,
    name: "BOD",
    date: new Date("2025-02-14"),
    time: "01:00 PM",
    type: "Automatic",
    page: 262,
    line: 34,
    verified: "Check-in sheet",
    by: "Admin",
  },
  {
    id: 10,
    name: "BOD",
    date: new Date("2025-02-14"),
    time: "02:00 PM",
    type: "General",
    page: 262,
    line: 34,
    verified: "QR Code",
    by: "Admin",
  },
  {
    id: 11,
    name: "GMM",
    date: new Date("2025-02-14"),
    time: "11:00 AM",
    type: "General",
    page: 262,
    line: 34,
    verified: "QR Code",
    by: "Admin",
  },
];

export const meetingTypeOptions = ["Automatic", "General"];
export const verifiedOptions = ["Check-in sheet", "QR Code"];
export const borderRight = "border-r-[1px] border-[#1b7398]";
