export const tabsData = [
  { id: "tab1", label: "Class List", placeholder: "Class Lookup" },
  { id: "tab2", label: "Training Course List", placeholder: "Course Lookup" },
  { id: "tab3", label: "Instructor List", placeholder: "Instructor Lookup" },
];

export const classListData = [
  { type: "All", name: "Anti-Harassment" },
  { type: "All", name: "Basic First Aid / Adult CPR / AED" },
  { type: "All", name: "Blue Print Reading Part 1" },
  { type: "All", name: "Blue Print Reading Part 2" },
  { type: "All", name: "Blue Print Reading Part 3" },
  { type: "All", name: "Blue Print Reading Final" },
  { type: "CM", name: "ACI Concrete Flatwork Finisher & Technician" },
  { type: "CM - B1 - U01", name: "Industry Orientation" },
  { type: "CM - B1 - U02", name: "Production & History of Concrete" },
  { type: "CM - B1 - U03", name: "Workplace Safety & Health" },
  { type: "CM - B1 - U04", name: "Place and Leveling Concrete" },
];

export const borderRight = "border-r-[1px] border-[#1b7398]";

export const trainingCourseHeadData = [
  { id: 1, key: "type", label: "Type" },
  { id: 2, key: "name", label: "Class Name" },
  { id: 3, key: "date", label: "Date" },
  { id: 4, key: "time", label: "Time" },
  { id: 5, key: "hours", label: "Hours" },
  { id: 6, key: "instructor", label: "Instructor" },
];

export const trainingCourseCellData = [
  {
    id: 1,
    type: "ALL",
    name: "Respirator Fit - Half-Face & Particulate",
    date: "04/15/2025",
    time: "11:00 am",
    hours: 4,
    instructor: "Carl Allen",
  },
  {
    id: 2,
    type: "ALL",
    name: "Basic First Aid / Adult CPR / AED",
    date: "04/16/2025",
    time: "1:00 pm",
    hours: 8,
    instructor: "John Hollingsworth",
  },
  {
    id: 3,
    type: "ALL",
    name: "OSHA 30",
    date: "04/24/2025",
    time: "3:00 pm",
    hours: 30,
    instructor: "John Hollingsworth",
  },
  {
    id: 4,
    type: "ALL",
    name: "Respirator Fit - Half-Face & Particulates",
    date: "04/28/2025",
    time: "1:00 pm",
    hours: 4,
    instructor: "Carl Allen",
  },
  {
    id: 5,
    type: "ALL",
    name: "OSHA 10",
    date: "05/04/2025",
    time: "2:00 pm",
    hours: 10,
    instructor: "John Hollingsworth",
  },
  {
    id: 6,
    type: "PL",
    name: "Blue Print Reading Part 1",
    date: "05/09/2025",
    time: "12:00 pm",
    hours: 5,
    instructor: "Emily Carson",
  },
  {
    id: 7,
    type: "ALL",
    name: "Basic First Aid / Adult CPR / AED",
    date: "05/16/2025",
    time: "1:00 pm",
    hours: 6,
    instructor: "John Hollingsworth",
  },
  {
    id: 8,
    type: "ALL",
    name: "Industry Orientation",
    date: "05/19/2025",
    time: "11:00 am",
    hours: 2,
    instructor: "Carl Allen",
  },
  {
    id: 9,
    type: "ALL",
    name: "Blue Print Reading Part 2",
    date: "06/15/2025",
    time: "10:00 am",
    hours: 6,
    instructor: "Emily Carson",
  },
  {
    id: 10,
    type: "CM",
    name: "Blue Print Reading",
    date: "06/30/2025",
    time: "9:00 pm",
    hours: 30,
    instructor: "Emily Carson",
  },
  {
    id: 11,
    type: "ALL",
    name: "Place and Leveling Concrete",
    date: "07/15/2025",
    time: "9:00 am",
    hours: 8,
    instructor: "Carl Allen",
  },
];

export const instructorHeadData = [
  { id: 1, label: "First Name", key: "firstName" },
  { id: 2, label: "Last Name", key: "lastName" },
  { id: 3, label: "Email", key: "email" },
  { id: 4, label: "Phone", key: "phone" },
  { id: 5, label: "Location", key: "location" },
];

export const instructorCellData = [
  {
    id: 1,
    firstName: "Lauren",
    lastName: "Abbott",
    email: "labbott@email.com",
    phone: "(555) 454-4444",
    location: "Boulder County",
  },
  {
    id: 2,
    firstName: "Kevin",
    lastName: "Smith",
    email: "ksmith@email.com",
    phone: "(555) 454-1221",
    location: "Boulder County",
  },
  {
    id: 3,
    firstName: "John",
    lastName: "Hollingsworth",
    email: "mholling@email.com",
    phone: "(555) 450-7645",
    location: "Boulder County",
  },
  {
    id: 4,
    firstName: "Shane",
    lastName: "Edwards",
    email: "sedwards@email.com",
    phone: "(555) 450-1535",
    location: "Boulder County",
  },
  {
    id: 5,
    firstName: "Adrian",
    lastName: "Stephens",
    email: "Astephens@email.com",
    phone: "(555) 454-0926",
    location: "Denver County",
  },
  {
    id: 6,
    firstName: "Liz",
    lastName: "Diaz",
    email: "ldiaz@email.com",
    phone: "(555) 454-9241",
    location: "Denver County",
  },
  {
    id: 7,
    firstName: "Emily",
    lastName: "Carson",
    email: "ecarson@email.com",
    phone: "(555) 454-9045",
    location: "Denver County",
  },
  {
    id: 8,
    firstName: "Carl",
    lastName: "Allen",
    email: "callen@email.com",
    phone: "(555) 454-8365",
    location: "Denver County",
  },
  {
    id: 9,
    firstName: "Mark",
    lastName: "Ryan",
    email: "ksmith@email.com",
    phone: "(555) 454-1956",
    location: "Larimer County",
  },
];
