export const fieldHeadData = [
  { id: "project", label: "Project" },
  { id: "contractor", label: "Contractor" },
  { id: "startDate", label: "Start Date" },
  { id: "requestDate", label: "Request Date" },
  { id: "requestBy", label: "Request By" },
  { id: "comments", label: "Comments" },
  { id: "actions", label: "Actions" },
];

export const fieldCellData = [
  {
    id: 1,
    project: "NH Station",
    contractor: "ACME Construction LTD",
    startDate: "04-15-2025",
    requestDate: "04-15-2025",
    requestBy: "Charles Duncan",
    comments: "",
  },
  {
    id: 2,
    project: "Clear to Yard",
    contractor: "Adams Construction LLC",
    startDate: "04-16-2025",
    requestDate: "04-16-2025",
    requestBy: "Charles Duncan",
    comments: "",
  },
  {
    id: 3,
    project: "Fab Bowling",
    contractor: "ABC Concrete",
    startDate: "04-24-2025",
    requestDate: "04-24-2025",
    requestBy: "Harry Williams",
    comments: "",
  },
  {
    id: 4,
    project: "Centennial Pool",
    contractor: "Jones Bros Concrete",
    startDate: "04-28-2025",
    requestDate: "04-28-2025",
    requestBy: "Harry Williams",
    comments: "Report to John W",
  },
  {
    id: 5,
    project: "Clear to Yard",
    contractor: "Altitude Construction",
    startDate: "05-04-2025",
    requestDate: "05-04-2025",
    requestBy: "Charles Duncan",
    comments: "",
  },
  {
    id: 6,
    project: "Railroad Museum",
    contractor: "Smith Construction LTD",
    startDate: "05-09-2025",
    requestDate: "05-09-2025",
    requestBy: "Harry Williams",
    comments: "",
  },
  {
    id: 7,
    project: "StVrain School",
    contractor: "Jones Concrete",
    startDate: "05-16-2025",
    requestDate: "05-16-2025",
    requestBy: "Larry Neville",
    comments: "Request Apprentice",
  },
  {
    id: 8,
    project: "HQ Office",
    contractor: "Blue River Construction",
    startDate: "05-19-2025",
    requestDate: "05-19-2025",
    requestBy: "Charles Duncan",
    comments: "",
  },
  {
    id: 9,
    project: "Clear to Yard",
    contractor: "Jones Bros Concrete",
    startDate: "06-15-2025",
    requestDate: "06-15-2025",
    requestBy: "Harry Williams",
    comments: "",
  },
  {
    id: 10,
    project: "Clear to Yard",
    contractor: "Evergreen Construction",
    startDate: "06-30-2025",
    requestDate: "06-30-2025",
    requestBy: "Larry Neville",
    comments: "Report to Steve",
  },
  {
    id: 11,
    project: "Sunset Pool",
    contractor: "ABC Concrete",
    startDate: "07-15-2025",
    requestDate: "07-15-2025",
    requestBy: "Larry Neville",
    comments: "",
  },
];
