export const taskData = [
  {
    id: 1,
    task: "Initiation",
    startDate: "12/29/2024",
    meetingDate: "-",
    responseDue: "-",
    responseDate: "-",
    status: "Completed",
    assignedTo: "Admin",
  },
  {
    id: 2,
    task: "Step 1",
    startDate: "01/02/2025",
    meetingDate: "01/06/2025",
    responseDue: "01/09/2025",
    responseDate: "01/08/2025",
    status: "Completed",
    assignedTo: "Admin",
  },
  {
    id: 3,
    task: "Step 2",
    startDate: "01/13/2025",
    meetingDate: "-",
    responseDue: "01/32/2025",
    responseDate: "-",
    status: "In Process",
    assignedTo: "Admin",
  },
  {
    id: 4,
    task: "Step 3",
    startDate: "-",
    meetingDate: "-",
    responseDue: "-",
    responseDate: "-",
    status: "Not Started",
    assignedTo: "Admin",
  },
  {
    id: 5,
    task: "Arbitration",
    startDate: "-",
    meetingDate: "-",
    responseDue: "-",
    responseDate: "-",
    status: "Not Started",
    assignedTo: "Admin",
  },
];
